name: krkrsdl2-x64

on:
  workflow_dispatch:
    branch: master

jobs:
  build:
    name: 编译构建
    runs-on: ubuntu-latest
    container: linuxdeepin/deepin:crimson-amd64-v1.6.0

    steps:
    - name: 检查代码
      uses: actions/checkout@v4

    - name: 安装所需依赖
      run: |
        apt update && apt upgrade -y
        apt install -y \
          build-essential cmake libasound2-dev libfreetype6-dev libjpeg-dev libpng-dev libvorbis-dev libx11-dev \
          libsdl2-dev libsdl2-*-dev unzip libavformat-dev libavcodec-dev libswscale-dev libswresample-dev libavutil-dev \
          ninja-build pkg-config

    - name: 编译
      continue-on-error: false
      run: |
        unzip external/*.zip -d external
        cmake -S . -B build
        cmake --build build

    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: krkrsdl2-x64
        path: ./build
